### ISSUE TITLE
如何连接互联网

### ISSUE THREAD

**Issue by joshua19881228** [joyqat/ps-hotspot#1]
您好，请问
1. 该脚本是不是无论如何都会建立一个不能连互联网的loop adapter
2. 如果本机已联互联网，如何修改才能支持通过该脚本提供的热点，让其他设备联互联网

**Comment by joyqat** [comment]
1. 是
2. 修改https://github.com/joyqat/ps-hotspot/blob/master/starthotspot.ps1#L47  ，使其匹配可以上网的网卡

**Comment by joshua19881228** [comment]
好的，谢谢，已经连接成功
